version: "3"
services:
  api:
    build: https://Xmaxer:${PAT}@github.com/Xmaxer/pm_app_api.git
    env_file: .env
    ports:
      - "4001:3000"
    depends_on:
      - postgres
      - redis
      - grpc
  client:
    build: https://Xmaxer:${PAT}@github.com/Xmaxer/pm_app.git
    env_file: .env
    ports:
      - "4002:3000"
    depends_on:
      - api
  postgres:
    image: postgres
    ports:
      - "4003:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DATABASE_PASSWORD}
      - POSTGRES_USER=${POSTGRES_DATABASE_USERNAME}
  redis:
    image: redis
    ports:
      - "4004:6379"
  influx:
    image: influxdb
    ports:
      - "4005:8086"
    volumes:
      - ./influx_setup.iql:/docker-entrypoint-initdb.d/influx_setup.iql
      - ./influxdb.conf:/influxdb.conf
    command: influxd -config influxdb.conf
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUX_DATABASE_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_DATABASE_PASSWORD}
  grpc:
    build: https://Xmaxer:${PAT}@github.com/Xmaxer/pm_app_grpc_server.git
    env_file: .env
    ports:
      - "4006:50051"
    depends_on:
      - influx
  grafana:
    image: grafana/grafana
    ports:
      - "4007:3000"
    depends_on:
      - influx